behaviors:
  AsteroidsPPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 3e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000